spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Hive  # Replace with your MySQL database URL
    username: root # Replace with your MySQL username
    password: root # Replace with your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver
  jpa:
    hibernate:
      ddl-auto: update  # Set to 'update' for automatic schema generation or 'none' if you want to manage it manually
    defer-datasource-initialization: true
    show-sql: true
 # sql:
 #   init:
 #     mode: always  # To ensure SQL scripts are run on startup (if any)

  # Disable H2 console for MySQL
  h2:
    console:
      enabled: false

server:
  port: 9092  # Your server port
